# acesso via loadbalancer ao backend via porta 80

apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

  

